{% set name = "prince" %}
{% set version = "0.20.2" %}

package:
  name: {{ name|lower }}-factor-analysis
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e39f1b149ddaa5ac4d57f6a6e1858c1e6af4c75b3b811d9820f2812c2784891

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - altair >=5.0.0
    - pandas >=2.2.0
    - scikit-learn >=1.5.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - prince
  commands:
    - pip check

about:
  home: https://github.com/MaxHalford/prince
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Statistical factor analysis in Python
  doc_url: https://github.com/MaxHalford/prince
  dev_url: https://github.com/MaxHalford/prince

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - rluria14
    - benhuff
    - MaxHalford
