{% set name = "prince" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}-factor-analysis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 361aa1d2d6de232fe512c5d94dae78d11b35ea9f2ab2c5d21e53c8906bc3565a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - pip
    - python >=3.0
    - setuptools

  run:
    - matplotlib-base >=3.0.2
    - numpy >=1.16.1
    - pandas >=0.24.0
    - python >=3.0
    - scikit-learn >=0.20.1
    - scipy >=1.1.0

test:
  imports:
    - prince

about:
  home: https://github.com/MaxHalford/prince
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Statistical factor analysis in Python
  doc_url: https://pypi.org/project/prince/
  dev_url: https://github.com/MaxHalford/prince

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - rluria14
    - benhuff
